// JavaScript Document
$(function(){
	$(".m1").hover(function(){
		$(this).children("a").animate({top:"-48px"},120);
		$(".t1").fadeIn(60);
		$(".t1").animate({top:"5px"},60);
		},function(){
			$(this).children("a").animate({top:"0"},120);
			$(".t1").animate({top:"0"},60);
			$(".t1").fadeOut(60);
			});
	$(".m2").hover(function(){
		$(this).children("a").animate({top:"-48px"},120);
		$(".t2").fadeIn(60);
		$(".t2").animate({top:"5px"},60);
		},function(){
			$(this).children("a").animate({top:"0"},120);
			$(".t2").animate({top:"0"},60);
			$(".t2").fadeOut(60);
			});
	$(".m3").hover(function(){
		$(this).children("a").animate({top:"-48px"},120);
		$(".t3").fadeIn(60);
		$(".t3").animate({top:"5px"},60);
		},function(){
			$(this).children("a").animate({top:"0"},120);
			$(".t3").animate({top:"0"},60);
			$(".t3").fadeOut(60);
			});
	$(".m4").hover(function(){
		$(this).children("a").animate({top:"-48px"},120);
		$(".t4").fadeIn(60);
		$(".t4").animate({top:"5px"},60);
		},function(){
			$(this).children("a").animate({top:"0"},120);
			$(".t4").animate({top:"0"},60);
			$(".t4").fadeOut(60);
			});
	})