<table width="100%" height="64" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td bgcolor="#<%=(base.Fields.Item("seasoncolor").Value)%>" class="tt_title">&nbsp;<span onclick="javascript:window.open('http://<%=(base.Fields.Item("address").Value)%>/')"><%=(base.Fields.Item("blogtitle").Value)%></span></td>
    <td width="100" background="image/right.gif" bgcolor="#<%=(base.Fields.Item("seasoncolor").Value)%>"><DIV align=right><FONT color=#ffffff>QQ</FONT> <A href="http://wpa.qq.com/msgrd?V=1&amp;Uin=369880993&amp;Menu=yes" target=_blank><FONT color=#ffffff>3698</FONT><FONT color=#<%=(base.Fields.Item("seasoncolor").Value)%>>80993</FONT></A>&nbsp;&nbsp;</DIV></td>
  </tr>
</table>